spring:
  flyway:
    locations: classpath:db/migration,classpath:db/demo

commerce:
  bootstrap:
    enabled: true
    admin-email: ${DEMO_ADMIN_EMAIL:admin@aurora.local}
    admin-password: ${DEMO_ADMIN_PASSWORD:Aurora@2026}

info:
  app:
    stage: demo
